import type {
  Claim,
  CommunitySummary,
  EventCategory,
  EventDetail,
  EventStatus,
  Evidence,
  TimelineEntry,
  VerificationState,
} from "./index";

/**
 * DEMO DATA. Every event is flagged `is_demo: true` and every source lives on
 * the reserved `.example` top-level domain (RFC 2606), so no demo citation can
 * resolve to, or be mistaken for, a real publication. Timestamps are generated
 * relative to "now" so the demo always looks current; it is still not real.
 */

const MINUTE = 60_000;

export const demoEventId = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`;

interface Clock {
  ago(minutes: number): string;
  ahead(minutes: number): string;
  /** A date-only value `days` before now: 00:00 UTC of that calendar date (use with published_at_precision "day"). */
  day(days: number): string;
}

function makeClock(now: Date): Clock {
  const t = now.getTime();
  return {
    ago: (m) => new Date(t - m * MINUTE).toISOString(),
    ahead: (m) => new Date(t + m * MINUTE).toISOString(),
    day: (d) => new Date(t - d * 24 * 60 * MINUTE).toISOString().slice(0, 10) + "T00:00:00.000Z",
  };
}

type EvidenceInput = Omit<
  Evidence,
  "id" | "event_id" | "publisher" | "agent_note" | "location_match" | "time_match" | "source_domain" | "published_at_precision" | "found_via"
> &
  Partial<Pick<Evidence, "publisher" | "agent_note" | "location_match" | "time_match" | "published_at_precision" | "found_via">>;

function evidenceFor(eventId: string, items: EvidenceInput[]): Evidence[] {
  return items.map((item, i) => ({
    id: `${eventId.slice(-3)}-ev-${i + 1}`,
    event_id: eventId,
    publisher: item.publisher ?? null,
    agent_note: item.agent_note ?? null,
    location_match: item.location_match ?? "near",
    time_match: item.time_match ?? "current",
    source_domain: item.source_url ? new URL(item.source_url).hostname : null,
    published_at_precision: item.published_at_precision ?? (item.published_at ? "instant" : null),
    found_via: item.found_via ?? (item.source_type === "community_report" ? "community_report" : "web_search"),
    ...item,
  }));
}

type TimelineInput = Omit<TimelineEntry, "id" | "detail" | "from_status" | "to_status" | "evidence_id"> &
  Partial<Pick<TimelineEntry, "detail" | "from_status" | "to_status" | "evidence_id">>;

function timelineFor(eventId: string, items: TimelineInput[]): TimelineEntry[] {
  return items.map((item, i) => ({
    id: `${eventId.slice(-3)}-tl-${i + 1}`,
    detail: null,
    from_status: null,
    to_status: null,
    evidence_id: null,
    ...item,
  }));
}

function community(partial: Partial<CommunitySummary> & { yes?: number; no?: number; unsure?: number }): CommunitySummary {
  return {
    window_minutes: partial.window_minutes ?? 60,
    recent_confirmations: partial.recent_confirmations ?? 0,
    recent_disputes: partial.recent_disputes ?? 0,
    resolved_reports: partial.resolved_reports ?? 0,
    still_happening: { yes: partial.yes ?? 0, no: partial.no ?? 0, not_sure: partial.unsure ?? 0 },
  };
}

interface EventInput {
  n: number;
  title: string;
  summary: string;
  category: EventCategory;
  lat: number;
  lng: number;
  approximate_location: string;
  radius_m?: number;
  status: EventStatus;
  verification_state: VerificationState;
  origin: EventDetail["origin"];
  first_seen_at: string;
  last_updated_at: string;
  last_verified_at: string | null;
  last_checked_at: string | null;
  scheduled_start_at?: string;
  scheduled_end_at?: string;
  expires_at?: string;
  community_confirmation_count: number;
  community_dispute_count: number;
  evidence_summary: string | null;
  claims: Omit<Claim, "id">[];
  evidence: EvidenceInput[];
  timeline: TimelineInput[];
  community: CommunitySummary;
}

function buildEvent(input: EventInput): EventDetail {
  const id = demoEventId(input.n);
  const evidence = evidenceFor(id, input.evidence);
  return {
    id,
    title: input.title,
    summary: input.summary,
    category: input.category,
    coordinates: { latitude: input.lat, longitude: input.lng },
    approximate_location: input.approximate_location,
    affected_area: input.radius_m ? { radius_m: input.radius_m } : null,
    status: input.status,
    verification_state: input.verification_state,
    origin: input.origin,
    source_count: evidence.length,
    independent_source_count: evidence.filter((e) => e.counts_as_independent).length,
    community_confirmation_count: input.community_confirmation_count,
    community_dispute_count: input.community_dispute_count,
    first_seen_at: input.first_seen_at,
    last_updated_at: input.last_updated_at,
    last_verified_at: input.last_verified_at,
    last_checked_at: input.last_checked_at,
    scheduled_start_at: input.scheduled_start_at ?? null,
    scheduled_end_at: input.scheduled_end_at ?? null,
    expires_at: input.expires_at ?? null,
    is_demo: true,
    current_claims: input.claims.map((c, i) => ({ ...c, id: `${id.slice(-3)}-cl-${i + 1}` })),
    evidence_summary: input.evidence_summary,
    evidence,
    timeline: timelineFor(id, input.timeline),
    community: input.community,
  };
}

export function buildDemoEvents(now: Date): EventDetail[] {
  const c = makeClock(now);

  return [
    buildEvent({
      n: 101,
      title: "US-101 northbound closed near Cesar Chavez St",
      summary:
        "Northbound lanes of US-101 are closed near the Cesar Chavez St interchange after a vehicle fire. Traffic is being diverted onto surface streets.",
      category: "road_closure",
      lat: 37.7489,
      lng: -122.4045,
      approximate_location: "US-101 at Cesar Chavez St interchange",
      radius_m: 600,
      status: "VERIFIED",
      verification_state: "idle",
      origin: "community_report",
      first_seen_at: c.ago(52),
      last_updated_at: c.ago(31),
      last_verified_at: c.ago(4),
      last_checked_at: c.ago(4),
      community_confirmation_count: 3,
      community_dispute_count: 0,
      evidence_summary:
        "Supported by an official transportation source updated 18 minutes ago and by independent local news coverage. One more article repeats the local news report, so it isn't counted separately.",
      claims: [
        { text: "Northbound US-101 is closed at Cesar Chavez St", stance: "supported", evidence_ids: ["101-ev-1", "101-ev-2", "101-ev-3"] },
        { text: "The closure followed a vehicle fire", stance: "supported", evidence_ids: ["101-ev-1"] },
      ],
      evidence: [
        {
          source_type: "official_feed",
          source_name: "Demo: State transportation agency",
          source_url: "https://dot.state.example/incidents/demo-101",
          published_at: c.ago(18),
          retrieved_at: c.ago(4),
          quote: "Northbound US-101 closed at Cesar Chavez St due to a vehicle fire. Expect delays.",
          stance: "supports",
          source_class: "OFFICIAL",
          is_primary: true,
          lineage_id: "101-official",
          counts_as_independent: true,
          freshness_state: "fresh",
          location_match: "exact",
        },
        {
          source_type: "news_article",
          source_name: "Demo: Bay Area local news",
          source_url: "https://localnews.example/traffic/demo-101-closure",
          publisher: "Demo Local News",
          published_at: c.ago(41),
          retrieved_at: c.ago(4),
          quote: "Our reporter at the scene saw crews blocking all northbound lanes as smoke rose from a stalled vehicle.",
          stance: "supports",
          source_class: "LOCAL_NEWS",
          is_primary: true,
          lineage_id: "101-localnews",
          counts_as_independent: true,
          freshness_state: "fresh",
        },
        {
          source_type: "news_article",
          source_name: "Demo: Regional news aggregator",
          source_url: "https://aggregator.example/sf/demo-101-closure",
          published_at: c.ago(36),
          retrieved_at: c.ago(4),
          quote: "Crews blocked all northbound lanes as smoke rose from a stalled vehicle, according to local reports.",
          agent_note: "Repeats the local news report's wording and attribution; no new reporting.",
          stance: "supports",
          source_class: "REPUTABLE_NEWS",
          is_primary: false,
          lineage_id: "101-localnews",
          counts_as_independent: false,
          freshness_state: "fresh",
        },
        {
          source_type: "community_report",
          source_name: "Community reports",
          source_url: null,
          published_at: c.ago(52),
          retrieved_at: c.ago(52),
          quote: "Traffic stopped on 101 north, smoke near the Cesar Chavez exit.",
          stance: "supports",
          source_class: "COMMUNITY",
          is_primary: true,
          lineage_id: "101-community",
          counts_as_independent: true,
          freshness_state: "aging",
        },
      ],
      timeline: [
        { at: c.ago(52), kind: "report_received", label: "Community report received" },
        { at: c.ago(51), kind: "verification_started", label: "Verification started" },
        { at: c.ago(47), kind: "source_found", label: "Local news source found", evidence_id: "101-ev-2" },
        { at: c.ago(46), kind: "status_changed", label: "Status changed to Developing", from_status: "UNVERIFIED", to_status: "DEVELOPING" },
        { at: c.ago(31), kind: "source_found", label: "Official source confirms closure", evidence_id: "101-ev-1" },
        { at: c.ago(31), kind: "status_changed", label: "Status changed to Verified", from_status: "DEVELOPING", to_status: "VERIFIED", detail: "Fresh official evidence plus independent local reporting." },
        { at: c.ago(4), kind: "checked_no_change", label: "Sources re-checked — no change" },
      ],
      community: community({ recent_confirmations: 3, yes: 3, unsure: 1 }),
    }),

    buildEvent({
      n: 102,
      title: "Street flooding at Mission St & Cesar Chavez St",
      summary: "Standing water reported across several lanes near the intersection after heavy rain.",
      category: "flooding",
      lat: 37.748,
      lng: -122.4183,
      approximate_location: "Mission St near Cesar Chavez St",
      radius_m: 250,
      status: "DEVELOPING",
      verification_state: "idle",
      origin: "community_report",
      first_seen_at: c.ago(35),
      last_updated_at: c.ago(14),
      last_verified_at: c.ago(14),
      last_checked_at: c.ago(9),
      community_confirmation_count: 2,
      community_dispute_count: 0,
      evidence_summary:
        "Two independent reports describe standing water. No official source has confirmed flooding yet.",
      claims: [
        { text: "Water is covering lanes on Mission St", stance: "supported", evidence_ids: ["102-ev-1", "102-ev-2"] },
        { text: "A storm drain is overflowing", stance: "unconfirmed", evidence_ids: [] },
      ],
      evidence: [
        {
          source_type: "community_report",
          source_name: "Community reports",
          source_url: null,
          published_at: c.ago(35),
          retrieved_at: c.ago(35),
          quote: "Water is ankle deep in the right lane on Mission, cars slowing way down.",
          stance: "supports",
          source_class: "COMMUNITY",
          is_primary: true,
          lineage_id: "102-community",
          counts_as_independent: true,
          freshness_state: "aging",
        },
        {
          source_type: "social_post",
          source_name: "Demo: Public social post",
          source_url: "https://social.example/posts/demo-102",
          published_at: c.ago(16),
          retrieved_at: c.ago(14),
          quote: "Mission & Cesar Chavez is a lake right now. Avoid if you can.",
          stance: "supports",
          source_class: "SOCIAL",
          is_primary: true,
          lineage_id: "102-social",
          counts_as_independent: true,
          freshness_state: "fresh",
        },
      ],
      timeline: [
        { at: c.ago(35), kind: "report_received", label: "Community report received" },
        { at: c.ago(34), kind: "verification_started", label: "Verification started" },
        { at: c.ago(14), kind: "source_found", label: "Independent social post found", evidence_id: "102-ev-2" },
        { at: c.ago(14), kind: "status_changed", label: "Status changed to Developing", from_status: "UNVERIFIED", to_status: "DEVELOPING" },
        { at: c.ago(9), kind: "checked_no_change", label: "Sources re-checked — no official confirmation yet" },
      ],
      community: community({ recent_confirmations: 2, yes: 2 }),
    }),

    buildEvent({
      n: 103,
      title: "Multi-vehicle collision on Bay Bridge westbound",
      summary: "A collision is blocking at least one westbound lane near the Treasure Island tunnel.",
      category: "crash",
      lat: 37.8025,
      lng: -122.3665,
      approximate_location: "Bay Bridge westbound near Yerba Buena Island",
      radius_m: 800,
      status: "LIKELY",
      verification_state: "idle",
      origin: "source_discovered",
      first_seen_at: c.ago(25),
      last_updated_at: c.ago(11),
      last_verified_at: c.ago(11),
      last_checked_at: c.ago(6),
      community_confirmation_count: 1,
      community_dispute_count: 0,
      evidence_summary:
        "Local news and an independent eyewitness post both describe a collision. An official incident listing hasn't appeared yet, so this isn't marked verified.",
      claims: [
        { text: "A collision is blocking a westbound lane", stance: "supported", evidence_ids: ["103-ev-1", "103-ev-2"] },
      ],
      evidence: [
        {
          source_type: "news_article",
          source_name: "Demo: Bay Area local news",
          source_url: "https://localnews.example/traffic/demo-103-bay-bridge",
          published_at: c.ago(19),
          retrieved_at: c.ago(6),
          quote: "At least three vehicles were involved in a collision on the westbound span, blocking the left lane.",
          stance: "supports",
          source_class: "LOCAL_NEWS",
          is_primary: true,
          lineage_id: "103-localnews",
          counts_as_independent: true,
          freshness_state: "fresh",
        },
        {
          source_type: "social_post",
          source_name: "Demo: Public social post",
          source_url: "https://social.example/posts/demo-103",
          published_at: c.ago(23),
          retrieved_at: c.ago(11),
          quote: "Crash on the bridge westbound, left lane blocked, traffic crawling.",
          stance: "supports",
          source_class: "SOCIAL",
          is_primary: true,
          lineage_id: "103-social",
          counts_as_independent: true,
          freshness_state: "fresh",
        },
      ],
      timeline: [
        { at: c.ago(25), kind: "source_found", label: "Social post found by monitoring", evidence_id: "103-ev-2" },
        { at: c.ago(24), kind: "verification_started", label: "Verification started" },
        { at: c.ago(11), kind: "source_found", label: "Local news source found", evidence_id: "103-ev-1" },
        { at: c.ago(11), kind: "status_changed", label: "Status changed to Likely", from_status: "DEVELOPING", to_status: "LIKELY" },
        { at: c.ago(6), kind: "checked_no_change", label: "Sources re-checked — still no official listing" },
      ],
      community: community({ recent_confirmations: 1, yes: 1 }),
    }),

    buildEvent({
      n: 104,
      title: "Power outage in parts of the Inner Richmond",
      summary: "The utility reports an outage affecting several blocks. Estimated restoration is this evening.",
      category: "power_outage",
      lat: 37.78,
      lng: -122.465,
      approximate_location: "Inner Richmond, around Clement St",
      radius_m: 700,
      status: "VERIFIED",
      verification_state: "idle",
      origin: "source_discovered",
      first_seen_at: c.ago(80),
      last_updated_at: c.ago(30),
      last_verified_at: c.ago(12),
      last_checked_at: c.ago(12),
      community_confirmation_count: 5,
      community_dispute_count: 0,
      evidence_summary:
        "The utility's own outage map lists this outage, and nearby residents confirm it's still ongoing.",
      claims: [
        { text: "Power is out across several blocks", stance: "supported", evidence_ids: ["104-ev-1", "104-ev-2"] },
        { text: "Restoration is estimated for this evening", stance: "supported", evidence_ids: ["104-ev-1"] },
      ],
      evidence: [
        {
          source_type: "official_feed",
          source_name: "Demo: Utility outage map",
          source_url: "https://outages.utility.example/demo-104",
          published_at: c.ago(30),
          retrieved_at: c.ago(12),
          quote: "Outage affecting approximately 1,200 customers. Cause under investigation. Estimated restoration 7:30 PM.",
          stance: "supports",
          source_class: "FIRST_PARTY",
          is_primary: true,
          lineage_id: "104-utility",
          counts_as_independent: true,
          freshness_state: "fresh",
          location_match: "exact",
        },
        {
          source_type: "community_report",
          source_name: "Community reports",
          source_url: null,
          published_at: c.ago(20),
          retrieved_at: c.ago(20),
          quote: "Still dark on our block, traffic lights out at Clement.",
          stance: "supports",
          source_class: "COMMUNITY",
          is_primary: true,
          lineage_id: "104-community",
          counts_as_independent: true,
          freshness_state: "fresh",
        },
      ],
      timeline: [
        { at: c.ago(80), kind: "source_found", label: "Utility outage listing found", evidence_id: "104-ev-1" },
        { at: c.ago(78), kind: "status_changed", label: "Status changed to Verified", from_status: "UNVERIFIED", to_status: "VERIFIED", detail: "First-party utility listing is a primary source." },
        { at: c.ago(30), kind: "community_update", label: "Utility updated estimated restoration time" },
        { at: c.ago(12), kind: "checked_no_change", label: "Sources re-checked — outage still listed" },
      ],
      community: community({ recent_confirmations: 5, yes: 5, window_minutes: 90 }),
    }),

    buildEvent({
      n: 105,
      title: "N Judah delays near Cole Valley",
      summary: "Riders report long waits on the N Judah line, but the transit agency currently lists normal service.",
      category: "transit_disruption",
      lat: 37.7656,
      lng: -122.45,
      approximate_location: "N Judah line around Carl St & Cole St",
      status: "CONFLICTING",
      verification_state: "in_progress",
      origin: "community_report",
      first_seen_at: c.ago(55),
      last_updated_at: c.ago(10),
      last_verified_at: c.ago(48),
      last_checked_at: c.ago(10),
      community_confirmation_count: 3,
      community_dispute_count: 1,
      evidence_summary:
        "The transit agency's status page reports normal service, while recent community reports describe ongoing delays. Verity is re-checking sources.",
      claims: [
        { text: "N Judah trains are delayed", stance: "contradicted", evidence_ids: ["105-ev-1", "105-ev-2", "105-ev-3"] },
      ],
      evidence: [
        {
          source_type: "official_feed",
          source_name: "Demo: Transit agency service alerts",
          source_url: "https://alerts.transit.example/lines/n-judah",
          published_at: c.ago(10),
          retrieved_at: c.ago(10),
          quote: "N Judah: Service is running normally.",
          stance: "contradicts",
          source_class: "OFFICIAL",
          is_primary: true,
          lineage_id: "105-transit",
          counts_as_independent: true,
          freshness_state: "fresh",
        },
        {
          source_type: "news_article",
          source_name: "Demo: Bay Area local news",
          source_url: "https://localnews.example/transit/demo-105",
          published_at: c.ago(50),
          retrieved_at: c.ago(48),
          quote: "A stalled train near Cole Valley caused delays of up to 20 minutes on the N Judah.",
          stance: "supports",
          source_class: "LOCAL_NEWS",
          is_primary: true,
          lineage_id: "105-localnews",
          counts_as_independent: true,
          freshness_state: "aging",
          time_match: "recent",
        },
        {
          source_type: "community_report",
          source_name: "Community reports",
          source_url: null,
          published_at: c.ago(15),
          retrieved_at: c.ago(15),
          quote: "Waited 25 minutes at Carl & Cole, display says delayed.",
          stance: "supports",
          source_class: "COMMUNITY",
          is_primary: true,
          lineage_id: "105-community",
          counts_as_independent: true,
          freshness_state: "fresh",
        },
      ],
      timeline: [
        { at: c.ago(55), kind: "report_received", label: "Community report received" },
        { at: c.ago(54), kind: "verification_started", label: "Verification started" },
        { at: c.ago(48), kind: "source_found", label: "Local news source found", evidence_id: "105-ev-2" },
        { at: c.ago(48), kind: "status_changed", label: "Status changed to Developing", from_status: "UNVERIFIED", to_status: "DEVELOPING" },
        { at: c.ago(10), kind: "contradiction_found", label: "Transit agency lists normal service", evidence_id: "105-ev-1" },
        { at: c.ago(10), kind: "status_changed", label: "Status changed to Conflicting", from_status: "DEVELOPING", to_status: "CONFLICTING", detail: "A fresh official source contradicts recent community reports." },
        { at: c.ago(2), kind: "verification_started", label: "Re-verification started" },
      ],
      community: community({ recent_confirmations: 3, recent_disputes: 1, yes: 2, no: 1, unsure: 1 }),
    }),

    buildEvent({
      n: 106,
      title: "Giants vs. Dodgers at Oracle Park — heavy traffic expected",
      summary: "Evening game at Oracle Park. Expect heavy traffic and parking restrictions around the ballpark.",
      category: "sporting_event",
      lat: 37.7786,
      lng: -122.3893,
      approximate_location: "Oracle Park, King St & 3rd St",
      radius_m: 900,
      status: "VERIFIED",
      verification_state: "idle",
      origin: "source_discovered",
      first_seen_at: c.ago(60 * 26),
      last_updated_at: c.ago(60 * 5),
      last_verified_at: c.ago(25),
      last_checked_at: c.ago(25),
      scheduled_start_at: c.ahead(95),
      scheduled_end_at: c.ahead(95 + 190),
      expires_at: c.ahead(95 + 250),
      community_confirmation_count: 0,
      community_dispute_count: 0,
      evidence_summary: "Listed by the venue and covered by a city traffic advisory.",
      claims: [
        { text: "A game is scheduled at Oracle Park this evening", stance: "supported", evidence_ids: ["106-ev-1"] },
        { text: "Parking restrictions apply near the ballpark", stance: "supported", evidence_ids: ["106-ev-2"] },
      ],
      evidence: [
        {
          source_type: "web_page",
          source_name: "Demo: Ballpark event calendar",
          source_url: "https://ballpark.example/calendar/demo-106",
          published_at: c.ago(60 * 24 * 14),
          retrieved_at: c.ago(25),
          quote: "Giants vs. Dodgers — first pitch 7:15 PM. Gates open 5:45 PM.",
          stance: "supports",
          source_class: "FIRST_PARTY",
          is_primary: true,
          lineage_id: "106-venue",
          counts_as_independent: true,
          freshness_state: "fresh",
          location_match: "exact",
        },
        {
          source_type: "official_feed",
          source_name: "Demo: City traffic advisories",
          source_url: "https://traffic.city.example/advisories/demo-106",
          published_at: c.ago(60 * 5),
          retrieved_at: c.ago(25),
          quote: "Event parking restrictions in effect on King St and 3rd St from 4 PM.",
          stance: "supports",
          source_class: "OFFICIAL",
          is_primary: true,
          lineage_id: "106-city",
          counts_as_independent: true,
          freshness_state: "fresh",
        },
      ],
      timeline: [
        { at: c.ago(60 * 26), kind: "source_found", label: "Venue calendar listing found", evidence_id: "106-ev-1" },
        { at: c.ago(60 * 26), kind: "status_changed", label: "Status changed to Verified", from_status: "UNVERIFIED", to_status: "VERIFIED" },
        { at: c.ago(60 * 5), kind: "source_found", label: "City traffic advisory found", evidence_id: "106-ev-2" },
        { at: c.ago(25), kind: "checked_no_change", label: "Sources re-checked — no change" },
      ],
      community: community({}),
    }),

    buildEvent({
      n: 107,
      title: "Valencia Street fair — street closed to traffic",
      summary: "Valencia St is closed to cars between 16th and 20th St for a permitted street fair.",
      category: "festival",
      lat: 37.7605,
      lng: -122.4215,
      approximate_location: "Valencia St between 16th St and 20th St",
      radius_m: 500,
      status: "VERIFIED",
      verification_state: "idle",
      origin: "source_discovered",
      first_seen_at: c.ago(60 * 48),
      last_updated_at: c.ago(60 * 2),
      last_verified_at: c.ago(40),
      last_checked_at: c.ago(40),
      scheduled_start_at: c.ago(120),
      scheduled_end_at: c.ahead(240),
      expires_at: c.ahead(300),
      community_confirmation_count: 4,
      community_dispute_count: 0,
      evidence_summary: "The organizer's page and the city's street-closure permit both list today's closure.",
      claims: [
        { text: "Valencia St is closed between 16th and 20th St until evening", stance: "supported", evidence_ids: ["107-ev-1", "107-ev-2"] },
      ],
      evidence: [
        {
          source_type: "web_page",
          source_name: "Demo: Street fair organizer",
          source_url: "https://valenciafair.example/schedule",
          published_at: c.ago(60 * 24 * 10),
          retrieved_at: c.ago(40),
          quote: "Valencia St will be closed to traffic from 16th to 20th Street, 11 AM to 6 PM.",
          stance: "supports",
          source_class: "FIRST_PARTY",
          is_primary: true,
          lineage_id: "107-organizer",
          counts_as_independent: true,
          freshness_state: "fresh",
        },
        {
          source_type: "official_feed",
          source_name: "Demo: City street-closure permits",
          source_url: "https://permits.city.example/closures/demo-107",
          published_at: c.ago(60 * 24 * 7),
          retrieved_at: c.ago(40),
          quote: "Special event street closure: Valencia St, 16th St to 20th St.",
          stance: "supports",
          source_class: "OFFICIAL",
          is_primary: true,
          lineage_id: "107-city",
          counts_as_independent: true,
          freshness_state: "fresh",
          location_match: "exact",
        },
      ],
      timeline: [
        { at: c.ago(60 * 48), kind: "source_found", label: "City street-closure permit found", evidence_id: "107-ev-2" },
        { at: c.ago(60 * 48), kind: "status_changed", label: "Status changed to Verified", from_status: "UNVERIFIED", to_status: "VERIFIED" },
        { at: c.ago(120), kind: "community_update", label: "Event started on schedule" },
        { at: c.ago(40), kind: "checked_no_change", label: "Sources re-checked — no change" },
      ],
      community: community({ recent_confirmations: 4, yes: 4 }),
    }),

    buildEvent({
      n: 108,
      title: "Smoke reported near Twin Peaks",
      summary: "A community member reported smoke visible on the east side of Twin Peaks.",
      category: "fire",
      lat: 37.7544,
      lng: -122.4477,
      approximate_location: "East slope of Twin Peaks",
      radius_m: 400,
      status: "UNVERIFIED",
      verification_state: "in_progress",
      origin: "community_report",
      first_seen_at: c.ago(3),
      last_updated_at: c.ago(3),
      last_verified_at: null,
      last_checked_at: null,
      community_confirmation_count: 1,
      community_dispute_count: 0,
      evidence_summary: "Only one community report so far. Verity is checking live sources.",
      claims: [{ text: "Smoke is visible near Twin Peaks", stance: "unconfirmed", evidence_ids: ["108-ev-1"] }],
      evidence: [
        {
          source_type: "community_report",
          source_name: "Community report",
          source_url: null,
          published_at: c.ago(3),
          retrieved_at: c.ago(3),
          quote: "Gray smoke coming up from the east side of Twin Peaks, can see it from Market St.",
          stance: "supports",
          source_class: "COMMUNITY",
          is_primary: true,
          lineage_id: "108-community",
          counts_as_independent: true,
          freshness_state: "fresh",
        },
      ],
      timeline: [
        { at: c.ago(3), kind: "report_received", label: "Community report received" },
        { at: c.ago(2), kind: "verification_started", label: "Verification started" },
      ],
      community: community({ recent_confirmations: 1, yes: 1 }),
    }),

    buildEvent({
      n: 109,
      title: "Police activity near Civic Center Plaza",
      summary: "Several police vehicles reported near the plaza. Cause unknown.",
      category: "police_activity",
      lat: 37.7793,
      lng: -122.4176,
      approximate_location: "Civic Center Plaza",
      status: "UNVERIFIED",
      verification_state: "unavailable",
      origin: "community_report",
      first_seen_at: c.ago(30),
      last_updated_at: c.ago(22),
      last_verified_at: null,
      last_checked_at: c.ago(22),
      community_confirmation_count: 0,
      community_dispute_count: 0,
      evidence_summary: "One community report. Live sources couldn't be checked; nothing has been inferred.",
      claims: [{ text: "Police vehicles are gathered near the plaza", stance: "unconfirmed", evidence_ids: ["109-ev-1"] }],
      evidence: [
        {
          source_type: "community_report",
          source_name: "Community report",
          source_url: null,
          published_at: c.ago(30),
          retrieved_at: c.ago(30),
          quote: "Four or five police cars at the plaza, part of the sidewalk taped off.",
          stance: "supports",
          source_class: "COMMUNITY",
          is_primary: true,
          lineage_id: "109-community",
          counts_as_independent: true,
          freshness_state: "aging",
        },
      ],
      timeline: [
        { at: c.ago(30), kind: "report_received", label: "Community report received" },
        { at: c.ago(29), kind: "verification_started", label: "Verification started" },
        { at: c.ago(22), kind: "verification_unavailable", label: "Verification temporarily unavailable", detail: "Live sources couldn't be reached. Existing evidence is unchanged; a retry is scheduled." },
      ],
      community: community({}),
    }),

    buildEvent({
      n: 110,
      title: "Geary Blvd lane closure for utility work",
      summary: "One eastbound lane on Geary Blvd was listed as closed for utility work.",
      category: "construction",
      lat: 37.781,
      lng: -122.444,
      approximate_location: "Geary Blvd near Masonic Ave",
      radius_m: 300,
      status: "STALE",
      verification_state: "queued",
      origin: "source_discovered",
      first_seen_at: c.ago(60 * 30),
      last_updated_at: c.ago(60 * 3),
      last_verified_at: c.ago(60 * 20),
      last_checked_at: c.ago(60 * 3),
      expires_at: c.ago(60),
      community_confirmation_count: 0,
      community_dispute_count: 0,
      evidence_summary:
        "The permit that supported this closure has passed its listed end date. A re-check is scheduled before showing it as current again.",
      claims: [{ text: "One eastbound lane is closed", stance: "supported", evidence_ids: ["110-ev-1"] }],
      evidence: [
        {
          source_type: "official_feed",
          source_name: "Demo: City street-closure permits",
          source_url: "https://permits.city.example/closures/demo-110",
          published_at: c.ago(60 * 24 * 3),
          retrieved_at: c.ago(60 * 3),
          quote: "Lane closure, Geary Blvd eastbound at Masonic Ave, utility work. Ends 4 PM.",
          stance: "supports",
          source_class: "OFFICIAL",
          is_primary: true,
          lineage_id: "110-city",
          counts_as_independent: true,
          freshness_state: "stale",
          time_match: "outdated",
        },
      ],
      timeline: [
        { at: c.ago(60 * 30), kind: "source_found", label: "City permit found", evidence_id: "110-ev-1" },
        { at: c.ago(60 * 30), kind: "status_changed", label: "Status changed to Verified", from_status: "UNVERIFIED", to_status: "VERIFIED" },
        { at: c.ago(60), kind: "expected_end_passed", label: "Listed end time passed" },
        { at: c.ago(59), kind: "status_changed", label: "Status changed to Stale", from_status: "VERIFIED", to_status: "STALE", detail: "Supporting evidence is out of date; re-check queued." },
      ],
      community: community({}),
    }),

    buildEvent({
      n: 111,
      title: "March on Market Street",
      summary: "A march moved along Market St, briefly closing lanes between Montgomery St and Civic Center.",
      category: "protest",
      lat: 37.788,
      lng: -122.402,
      approximate_location: "Market St between Montgomery St and Civic Center",
      radius_m: 800,
      status: "RESOLVED",
      verification_state: "idle",
      origin: "source_discovered",
      first_seen_at: c.ago(170),
      last_updated_at: c.ago(42),
      last_verified_at: c.ago(42),
      last_checked_at: c.ago(42),
      community_confirmation_count: 2,
      community_dispute_count: 0,
      evidence_summary: "An official source reported the streets reopened, and community members confirmed it ended.",
      claims: [
        { text: "Lanes on Market St were closed for a march", stance: "supported", evidence_ids: ["111-ev-1"] },
        { text: "All lanes have reopened", stance: "ended", evidence_ids: ["111-ev-2", "111-ev-3"] },
      ],
      evidence: [
        {
          source_type: "news_article",
          source_name: "Demo: Bay Area local news",
          source_url: "https://localnews.example/city/demo-111-march",
          published_at: c.ago(150),
          retrieved_at: c.ago(140),
          quote: "Several hundred people marched east on Market St, temporarily closing lanes.",
          stance: "supports",
          source_class: "LOCAL_NEWS",
          is_primary: true,
          lineage_id: "111-localnews",
          counts_as_independent: true,
          freshness_state: "stale",
          time_match: "outdated",
        },
        {
          source_type: "official_feed",
          source_name: "Demo: City emergency management",
          source_url: "https://alerts.city.example/demo-111",
          published_at: c.ago(45),
          retrieved_at: c.ago(42),
          quote: "All lanes on Market St have reopened.",
          stance: "ended",
          source_class: "OFFICIAL",
          is_primary: true,
          lineage_id: "111-city",
          counts_as_independent: true,
          freshness_state: "fresh",
        },
        {
          source_type: "community_report",
          source_name: "Community reports",
          source_url: null,
          published_at: c.ago(44),
          retrieved_at: c.ago(44),
          quote: "March is over, Market is open again.",
          stance: "ended",
          source_class: "COMMUNITY",
          is_primary: true,
          lineage_id: "111-community",
          counts_as_independent: true,
          freshness_state: "fresh",
        },
      ],
      timeline: [
        { at: c.ago(170), kind: "source_found", label: "Local news source found", evidence_id: "111-ev-1" },
        { at: c.ago(160), kind: "status_changed", label: "Status changed to Verified", from_status: "DEVELOPING", to_status: "VERIFIED" },
        { at: c.ago(45), kind: "source_found", label: "Official source reports streets reopened", evidence_id: "111-ev-2" },
        { at: c.ago(42), kind: "status_changed", label: "Status changed to Resolved", from_status: "VERIFIED", to_status: "RESOLVED" },
      ],
      community: community({ resolved_reports: 2, no: 2 }),
    }),

    buildEvent({
      n: 112,
      title: "Concert at Chase Center — parking restrictions in Mission Bay",
      summary: "Evening concert at Chase Center. Event parking rules apply on surrounding streets.",
      category: "concert",
      lat: 37.768,
      lng: -122.3877,
      approximate_location: "Chase Center, 3rd St & 16th St",
      radius_m: 700,
      status: "VERIFIED",
      verification_state: "idle",
      origin: "source_discovered",
      first_seen_at: c.ago(60 * 72),
      last_updated_at: c.ago(60 * 6),
      last_verified_at: c.ago(55),
      last_checked_at: c.ago(55),
      scheduled_start_at: c.ahead(180),
      scheduled_end_at: c.ahead(360),
      expires_at: c.ahead(420),
      community_confirmation_count: 0,
      community_dispute_count: 0,
      evidence_summary: "Listed on the venue's calendar; the city has posted event parking rules.",
      claims: [{ text: "Event parking restrictions apply in Mission Bay tonight", stance: "supported", evidence_ids: ["112-ev-1", "112-ev-2"] }],
      evidence: [
        {
          source_type: "web_page",
          source_name: "Demo: Arena event calendar",
          source_url: "https://arena.example/events/demo-112",
          // A calendar listing states a date, not a time.
          published_at: c.day(30),
          published_at_precision: "day",
          retrieved_at: c.ago(55),
          quote: "Doors 7:00 PM. Show 8:00 PM.",
          stance: "supports",
          source_class: "FIRST_PARTY",
          is_primary: true,
          lineage_id: "112-venue",
          counts_as_independent: true,
          freshness_state: "fresh",
          location_match: "exact",
        },
        {
          source_type: "official_feed",
          source_name: "Demo: City traffic advisories",
          source_url: "https://traffic.city.example/advisories/demo-112",
          published_at: c.ago(60 * 6),
          retrieved_at: c.ago(55),
          quote: "Event parking restrictions in Mission Bay from 5 PM to midnight.",
          stance: "supports",
          source_class: "OFFICIAL",
          is_primary: true,
          lineage_id: "112-city",
          counts_as_independent: true,
          freshness_state: "fresh",
        },
      ],
      timeline: [
        { at: c.ago(60 * 72), kind: "source_found", label: "Venue calendar listing found", evidence_id: "112-ev-1" },
        { at: c.ago(60 * 72), kind: "status_changed", label: "Status changed to Verified", from_status: "UNVERIFIED", to_status: "VERIFIED" },
        { at: c.ago(60 * 6), kind: "source_found", label: "City parking advisory found", evidence_id: "112-ev-2" },
        { at: c.ago(55), kind: "checked_no_change", label: "Sources re-checked — no change" },
      ],
      community: community({}),
    }),

    buildEvent({
      n: 113,
      title: "Heavy congestion on Van Ness Ave",
      summary: "Drivers report stop-and-go traffic on northbound Van Ness Ave.",
      category: "parking_traffic",
      lat: 37.7857,
      lng: -122.4213,
      approximate_location: "Van Ness Ave between Geary Blvd and California St",
      status: "DEVELOPING",
      verification_state: "idle",
      origin: "community_report",
      first_seen_at: c.ago(20),
      last_updated_at: c.ago(8),
      last_verified_at: c.ago(8),
      last_checked_at: c.ago(8),
      community_confirmation_count: 2,
      community_dispute_count: 0,
      evidence_summary: "Two separate community reports describe congestion. No cause has been confirmed.",
      claims: [{ text: "Northbound Van Ness Ave is congested", stance: "supported", evidence_ids: ["113-ev-1"] }],
      evidence: [
        {
          source_type: "community_report",
          source_name: "Community reports",
          source_url: null,
          published_at: c.ago(20),
          retrieved_at: c.ago(20),
          quote: "Van Ness northbound barely moving from Geary.",
          stance: "supports",
          source_class: "COMMUNITY",
          is_primary: true,
          lineage_id: "113-community",
          counts_as_independent: true,
          freshness_state: "fresh",
        },
      ],
      timeline: [
        { at: c.ago(20), kind: "report_received", label: "Community report received" },
        { at: c.ago(19), kind: "verification_started", label: "Verification started" },
        { at: c.ago(8), kind: "report_merged", label: "Second report merged into this event" },
        { at: c.ago(8), kind: "status_changed", label: "Status changed to Developing", from_status: "UNVERIFIED", to_status: "DEVELOPING" },
      ],
      community: community({ recent_confirmations: 2, yes: 2 }),
    }),

    buildEvent({
      n: 114,
      title: "Water main break on Folsom St",
      summary: "A reported water main break that sources did not support.",
      category: "other",
      lat: 37.77,
      lng: -122.413,
      approximate_location: "Folsom St near 11th St",
      status: "REJECTED",
      verification_state: "idle",
      origin: "community_report",
      first_seen_at: c.ago(140),
      last_updated_at: c.ago(100),
      last_verified_at: null,
      last_checked_at: c.ago(100),
      community_confirmation_count: 0,
      community_dispute_count: 3,
      evidence_summary:
        "The water utility reported no break in this area, and three community members said the water came from street cleaning.",
      claims: [{ text: "A water main broke on Folsom St", stance: "contradicted", evidence_ids: ["114-ev-1", "114-ev-2"] }],
      evidence: [
        {
          source_type: "official_feed",
          source_name: "Demo: Water utility service notices",
          source_url: "https://water.utility.example/notices",
          published_at: c.ago(105),
          retrieved_at: c.ago(100),
          quote: "No active main breaks reported in the South of Market area.",
          stance: "contradicts",
          source_class: "FIRST_PARTY",
          is_primary: true,
          lineage_id: "114-utility",
          counts_as_independent: true,
          freshness_state: "aging",
        },
        {
          source_type: "community_report",
          source_name: "Community reports",
          source_url: null,
          published_at: c.ago(120),
          retrieved_at: c.ago(120),
          quote: "That's the street sweeper truck flushing the gutter, not a main break.",
          stance: "contradicts",
          source_class: "COMMUNITY",
          is_primary: true,
          lineage_id: "114-community",
          counts_as_independent: true,
          freshness_state: "aging",
        },
      ],
      timeline: [
        { at: c.ago(140), kind: "report_received", label: "Community report received" },
        { at: c.ago(139), kind: "verification_started", label: "Verification started" },
        { at: c.ago(120), kind: "community_update", label: "Community members disputed the report" },
        { at: c.ago(100), kind: "contradiction_found", label: "Water utility reports no break in the area", evidence_id: "114-ev-1" },
        { at: c.ago(100), kind: "status_changed", label: "Status changed to Rejected", from_status: "UNVERIFIED", to_status: "REJECTED" },
      ],
      community: community({ recent_disputes: 3, no: 3, window_minutes: 180 }),
    }),

    buildEvent({
      n: 115,
      title: "Campus open house at SF State",
      summary: "Open house on campus today; expect more visitors and busier parking near 19th Ave.",
      category: "campus_event",
      lat: 37.7241,
      lng: -122.4799,
      approximate_location: "SF State campus, 19th Ave & Holloway Ave",
      radius_m: 600,
      status: "VERIFIED",
      verification_state: "idle",
      origin: "source_discovered",
      first_seen_at: c.ago(60 * 24 * 3),
      last_updated_at: c.ago(60 * 24),
      last_verified_at: c.ago(90),
      last_checked_at: c.ago(90),
      scheduled_start_at: c.ago(60),
      scheduled_end_at: c.ahead(180),
      expires_at: c.ahead(240),
      community_confirmation_count: 1,
      community_dispute_count: 0,
      evidence_summary: "Listed on the university's events page.",
      claims: [{ text: "An open house is happening on campus today", stance: "supported", evidence_ids: ["115-ev-1"] }],
      evidence: [
        {
          source_type: "web_page",
          source_name: "Demo: University events page",
          source_url: "https://events.university.example/open-house",
          published_at: c.ago(60 * 24 * 20),
          retrieved_at: c.ago(90),
          quote: "Fall Open House: tours, info sessions and department fairs, 10 AM – 3 PM.",
          stance: "supports",
          source_class: "FIRST_PARTY",
          is_primary: true,
          lineage_id: "115-university",
          counts_as_independent: true,
          freshness_state: "fresh",
        },
      ],
      timeline: [
        { at: c.ago(60 * 24 * 3), kind: "source_found", label: "University events listing found", evidence_id: "115-ev-1" },
        { at: c.ago(60 * 24 * 3), kind: "status_changed", label: "Status changed to Verified", from_status: "UNVERIFIED", to_status: "VERIFIED" },
        { at: c.ago(90), kind: "checked_no_change", label: "Sources re-checked — no change" },
      ],
      community: community({ recent_confirmations: 1, yes: 1, window_minutes: 120 }),
    }),
  ];
}
